import { useState, useEffect } from 'react'
import type { BrandData, Story } from '@/pages/Demo'

interface ContentTabProps {
  brandData: BrandData
  stories: Story[]
  onStoriesGenerated: (stories: Story[]) => void
  onStoryToggle: (storyId: string) => void
  onContinue: () => void
}

export function ContentTab({
  brandData,
  stories,
  onStoriesGenerated,
  onStoryToggle,
  onContinue,
}: ContentTabProps) {
  const [brief, setBrief] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)

  // Auto-generate stories when tab loads with scraped data
  useEffect(() => {
    if (!hasAutoGenerated && stories.length === 0 && (brandData.topics?.length || brandData.contentPreview)) {
      setHasAutoGenerated(true)
      handleGenerate()
    }
  }, [brandData, hasAutoGenerated, stories.length])

  const handleGenerate = async () => {
    setIsGenerating(true)
    
    // Simulate AI story generation
    await new Promise(resolve => setTimeout(resolve, 1500))
    
    // Generate stories based on scraped topics
    const generatedStories: Story[] = []
    const rawTopics = brandData.topics || []
    const industry = brandData.industry || 'General'
    const name = brandData.name || 'Your Brand'
    const tone = brandData.tone || 'Professional'
    
    // Filter out nav-like topics (single words, common nav items)
    const navWords = ['home', 'about', 'contact', 'services', 'team', 'blog', 'news', 'menu', 'login', 'sign', 'cart', 'search', 'faq', 'help', 'support', 'newsletter', 'subscribe', 'review', 'appointment', 'appointments']
    const topics = rawTopics.filter(topic => {
      const lower = topic.toLowerCase().trim()
      return topic.length > 15 && !navWords.includes(lower) && !navWords.some(nw => lower === nw + 's')
    })
    
    // Add stories based on FILTERED scraped topics (real content only)
    topics.forEach((topic, idx) => {
      if (idx < 3) {
        generatedStories.push({
          id: `topic-${idx}`,
          title: topic,
          introText: `Explore the latest insights about ${topic.toLowerCase()}. ${name} brings you in-depth coverage tailored for ${industry.toLowerCase()} professionals.`,
          selected: idx === 0, // Auto-select first topic
        })
      }
    })
    
    // Add standard newsletter sections
    const standardStories: Story[] = [
      {
        id: 'trends',
        title: `${industry} Trends to Watch`,
        introText: `Stay ahead of the curve with our analysis of the top trends shaping the ${industry.toLowerCase()} industry. From emerging technologies to shifting consumer behaviors, here's what ${name} customers need to know.`,
        selected: generatedStories.length === 0, // Select if no topic stories
      },
      {
        id: 'innovation',
        title: `How ${name} is Innovating`,
        introText: `Discover the latest innovations and initiatives driving ${name} forward. Our commitment to excellence continues to set new standards in the ${industry.toLowerCase()} space.`,
        selected: false,
      },
      {
        id: 'success',
        title: `Customer Success Story`,
        introText: `Learn how our partners are achieving remarkable results. This month, we spotlight a customer who leveraged ${name}'s solutions to achieve breakthrough success.`,
        selected: false,
      },
      {
        id: 'tips',
        title: `Expert Tips & Best Practices`,
        introText: `Our team of experts shares insider tips and best practices to help you maximize your ROI. These actionable strategies are designed for ${industry.toLowerCase()} professionals.`,
        selected: false,
      },
      {
        id: 'news',
        title: `Industry News Roundup`,
        introText: `Catch up on the latest developments in ${industry.toLowerCase()}. We've curated the most important stories and what they mean for your business.`,
        selected: false,
      },
    ]
    
    // Combine topic-based stories with standard ones, avoiding duplicates
    const allStories = [...generatedStories]
    for (const story of standardStories) {
      if (allStories.length < 7) {
        allStories.push(story)
      }
    }
    
    // Add tone-specific story
    if (tone === 'Casual & Friendly') {
      allStories.push({
        id: 'fun',
        title: `Fun Facts & Behind the Scenes`,
        introText: `Get to know the team behind ${name}! We're sharing some fun facts, team highlights, and a peek behind the curtain.`,
        selected: false,
      })
    } else if (tone === 'Enterprise') {
      allStories.push({
        id: 'whitepaper',
        title: `New Research & White Papers`,
        introText: `Access our latest research findings and white papers. Data-driven insights to inform your strategic decisions.`,
        selected: false,
      })
    }
    
    setIsGenerating(false)
    onStoriesGenerated(allStories)
  }

  const selectedCount = stories.filter(s => s.selected).length

  return (
    <div className="space-y-6">
      <div className="text-center mb-6">
        <h2 className="text-2xl font-bold text-gray-800">Content Brief</h2>
        <p className="text-gray-500 mt-1">
          {brandData.topics?.length 
            ? `We found ${brandData.topics.length} topics from your site. Select the stories you want.`
            : "Select the stories you'd like to include in your newsletter"}
        </p>
      </div>

      {/* Brand Summary */}
      <div className="bg-gradient-to-r from-purple-50 to-indigo-50 rounded-lg p-4 flex items-center gap-4">
        {brandData.logo ? (
          <img 
            src={brandData.logo} 
            alt={brandData.name} 
            className="w-12 h-12 object-contain rounded"
          />
        ) : (
          <div 
            className="w-12 h-12 rounded flex items-center justify-center text-white font-bold text-xl"
            style={{ 
              background: brandData.colors?.length 
                ? `linear-gradient(135deg, ${brandData.colors[0]}, ${brandData.colors[1] || brandData.colors[0]})`
                : 'linear-gradient(135deg, #667eea, #764ba2)'
            }}
          >
            {(brandData.name || 'B').charAt(0)}
          </div>
        )}
        <div className="flex-1">
          <h3 className="font-semibold text-gray-800">{brandData.name || 'Your Brand'}</h3>
          <p className="text-sm text-gray-500">
            {brandData.industry || 'General'} 
            {brandData.tone && ` • ${brandData.tone}`}
          </p>
          {brandData.scrapedDescription && (
            <p className="text-xs text-gray-400 mt-1 line-clamp-1">
              {brandData.scrapedDescription}
            </p>
          )}
        </div>
      </div>

      {/* Optional Brief Input */}
      <details className="group">
        <summary className="cursor-pointer text-sm text-purple-600 hover:text-purple-700 font-medium list-none flex items-center gap-2">
          <svg className="w-4 h-4 transition-transform group-open:rotate-90" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
          Add custom content brief (optional)
        </summary>
        <div className="mt-3">
          <textarea
            value={brief}
            onChange={(e) => setBrief(e.target.value)}
            rows={3}
            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent resize-none text-sm"
            placeholder="What topics, themes, or messages would you like to include? Any specific campaigns or announcements?"
          />
        </div>
      </details>

      {/* Generate Button - only if no stories yet */}
      {stories.length === 0 && !isGenerating && (
        <div className="flex justify-center">
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="px-8 py-3 bg-gradient-to-r from-purple-600 to-indigo-600 text-white font-medium rounded-lg hover:from-purple-700 hover:to-indigo-700 focus:ring-4 focus:ring-purple-500/50 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
          >
            ✨ Generate Story Ideas
          </button>
        </div>
      )}

      {/* Loading State */}
      {isGenerating && (
        <div className="flex flex-col items-center justify-center py-12">
          <svg className="animate-spin h-10 w-10 text-purple-600 mb-4" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
          <p className="text-gray-600 font-medium">Generating content ideas...</p>
          <p className="text-sm text-gray-400 mt-1">Building your personalized newsletter brief</p>
        </div>
      )}

      {/* Story Ideas */}
      {stories.length > 0 && !isGenerating && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold text-gray-800">
              Select stories for your newsletter
            </h3>
            <span className="text-sm text-purple-600 font-medium">
              {selectedCount} selected
            </span>
          </div>

          <div className="space-y-3 max-h-96 overflow-y-auto pr-2">
            {stories.map((story) => (
              <div
                key={story.id}
                onClick={() => onStoryToggle(story.id)}
                className={`p-4 border-2 rounded-lg cursor-pointer transition-all ${
                  story.selected
                    ? 'border-purple-500 bg-purple-50'
                    : 'border-gray-200 hover:border-gray-300'
                }`}
              >
                <div className="flex items-start gap-3">
                  <div className={`mt-1 w-5 h-5 rounded border-2 flex items-center justify-center flex-shrink-0 ${
                    story.selected 
                      ? 'bg-purple-500 border-purple-500' 
                      : 'border-gray-300'
                  }`}>
                    {story.selected && (
                      <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                      </svg>
                    )}
                  </div>
                  <div className="flex-1">
                    <h4 className="font-medium text-gray-800">{story.title}</h4>
                    <p className="text-sm text-gray-500 mt-1">{story.introText}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Regenerate & Continue */}
          <div className="flex justify-between pt-4 border-t">
            <button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="px-6 py-2 border border-gray-300 text-gray-700 font-medium rounded-lg hover:bg-gray-50 transition-all"
            >
              🔄 Regenerate
            </button>
            <button
              onClick={onContinue}
              disabled={selectedCount === 0}
              className="px-8 py-3 bg-gradient-to-r from-purple-600 to-indigo-600 text-white font-medium rounded-lg hover:from-purple-700 hover:to-indigo-700 focus:ring-4 focus:ring-purple-500/50 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
            >
              Continue to Features →
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
